# In-Game Account Switcher is a third-party mod for Minecraft Java Edition that
# allows you to change your logged in account in-game, without restarting it.
#
# Copyright (C) 2015-2022 The_Fireplace
# Copyright (C) 2021-2026 VidTu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

# Java:
# - Target: 25.0.2, released January 2026.
# - Update: February 2nd, 2026. (UTC)
# Vendors:
# - Eclipse Temurin: FreeBSD, Linux, UNIX, Windows (x86_64).
# - Azul Zulu: Windows (arm64).

toolchainUrl.FREE_BSD.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.FREE_BSD.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.LINUX.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.LINUX.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.MAC_OS.AARCH64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/mac/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.MAC_OS.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/mac/x64/jdk/hotspot/normal/eclipse
toolchainUrl.UNIX.AARCH64=https:\//api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/aarch64/jdk/hotspot/normal/eclipse
toolchainUrl.UNIX.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/linux/x64/jdk/hotspot/normal/eclipse
toolchainUrl.WINDOWS.AARCH64=https\://cdn.azul.com/zulu/bin/zulu25.32.21-ca-jdk25.0.2-win_aarch64.zip
toolchainUrl.WINDOWS.X86_64=https\://api.adoptium.net/v3/binary/version/jdk-25.0.2+10/windows/x64/jdk/hotspot/normal/eclipse
toolchainVersion=25
