/*
 * In-Game Account Switcher is a mod for Minecraft that allows you to change your logged in account in-game, without restarting Minecraft.
 * Copyright (C) 2015-2022 The_Fireplace
 * Copyright (C) 2021-2025 VidTu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>
 */

package ru.vidtu.ias;

import com.mojang.authlib.minecraft.UserApiService;
import com.mojang.authlib.yggdrasil.ProfileResult;
import net.minecraft.SharedConstants;
import net.minecraft.client.Minecraft;
import net.minecraft.client.User;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractSelectionList;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.ImageButton;
import net.minecraft.client.gui.components.Tooltip;
import net.minecraft.client.gui.components.WidgetSprites;
import net.minecraft.client.gui.components.events.GuiEventListener;
import net.minecraft.client.gui.components.toasts.SystemToast;
import net.minecraft.client.gui.components.toasts.ToastManager;
import net.minecraft.client.gui.layouts.LayoutElement;
import net.minecraft.client.gui.screens.ConnectScreen;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.screens.TitleScreen;
import net.minecraft.client.gui.screens.multiplayer.JoinMultiplayerScreen;
import net.minecraft.client.gui.screens.social.PlayerSocialManager;
import net.minecraft.client.multiplayer.ProfileKeyPairManager;
import net.minecraft.client.multiplayer.chat.report.ReportEnvironment;
import net.minecraft.client.multiplayer.chat.report.ReportingContext;
import net.minecraft.client.telemetry.ClientTelemetryManager;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.vidtu.ias.auth.LoginData;
import ru.vidtu.ias.auth.microsoft.MSAuth;
import ru.vidtu.ias.config.IASConfig;
import ru.vidtu.ias.config.IASStorage;
import ru.vidtu.ias.mixins.MinecraftAccessor;
import ru.vidtu.ias.screen.AccountScreen;
import ru.vidtu.ias.utils.Expression;
import ru.vidtu.ias.utils.Holder;
import ru.vidtu.ias.utils.IUtils;
import ru.vidtu.ias.utils.exceptions.FriendlyException;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * Main IAS class.
 *
 * @author VidTu
 */
public final class IAS {
    /**
     * Marker for all logs generated by the mod.
     */
    public static final Marker IAS_MARKER = MarkerManager.getMarker("MOD_IAS");

    /**
     * IAS static Microsoft application ID.
     */
    @NotNull
    public static final String CLIENT_ID = "54fd49e4-2103-4044-9603-2b028c814ec3";

    /**
     * Request timeout.
     */
    @NotNull
    public static final Duration TIMEOUT = Duration.ofSeconds(Long.getLong("ias.timeout", 15L));

    /**
     * Logger for this class.
     */
    @NotNull
    private static final Logger LOGGER = LoggerFactory.getLogger("IAS");

    /**
     * Template for {@link #userAgent}.
     */
    @NotNull
    private static final String USER_AGENT_TEMPLATE = "IAS/%s (https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher; %s; %s/%s; Minecraft/%s; Java/%s)";

    /**
     * IAS executor.
     */
    @Nullable
    private static ScheduledExecutorService executor;

    /**
     * Current IAS user agent.
     */
    @Nullable
    private static String userAgent;

    /**
     * Whether the mod is disabled remotely.
     */
    @SuppressWarnings("NegativelyNamedBooleanVariable") // <- The negative naming is intended.
    private static boolean disabled = false;

    /**
     * Toast for nick warning.
     */
    public static final SystemToast.SystemToastId NICK_WARN = new SystemToast.SystemToastId(10000L);

    /**
     * Button widget sprites.
     */
    private static final WidgetSprites BUTTON = new WidgetSprites(
            ResourceLocation.fromNamespaceAndPath("ias", "button_plain"),
            ResourceLocation.fromNamespaceAndPath("ias", "button_disabled"),
            ResourceLocation.fromNamespaceAndPath("ias", "button_focus")
    );

    /**
     * Text X.
     */
    private static int textX;

    /**
     * Text Y.
     */
    private static int textY;

    /**
     * Current text.
     */
    private static Component text = Component.translatable("ias.title", "(not loaded for some reason)");

    /**
     * An instance of this class cannot be created.
     *
     * @throws AssertionError Always
     */
    @Contract(value = "-> fail", pure = true)
    private IAS() {
        throw new AssertionError("No instances.");
    }

    /**
     * Initializes the IAS.
     *
     * @param version       Mod version
     * @param loader        Mod loader
     * @param loaderVersion Mod loader version
     * @param gameVersion   Game version
     */
    public static void init(@NotNull String version, @NotNull String loader, @NotNull String loaderVersion, @NotNull String gameVersion) {
        // Log.
        LOGGER.info("IAS: Initializing IAS...");

        // Set up IAS.
        UUID randomSessionId = UUID.randomUUID();
        userAgent = USER_AGENT_TEMPLATE.formatted(version, randomSessionId, loader, loaderVersion, gameVersion, Runtime.version().toString());
        LOGGER.debug("IAS: Current user agent: {}", userAgent);

        // Write the disclaimers.
        try {
            IASStorage.disclaimers();
        } catch (Throwable t) {
            LOGGER.error("IAS: Unable to write disclaimers.", t);
        }

        // Read the config.
        try {
            IASConfig.load();
        } catch (Throwable t) {
            LOGGER.error("IAS: Unable to load IAS config.", t);
        }

        // Read the storage.
        try {
            IASStorage.save();
        } catch (Throwable t) {
            LOGGER.error("IAS: Unable to load IAS storage.", t);
        }

        // Create the executor.
        executor = Executors.newSingleThreadScheduledExecutor(r -> new Thread(r, "IAS"));

        // Perform initial loading.
        if (Boolean.getBoolean("ias.skipDisableScanning")) {
            LOGGER.debug("IAS: Skipped IAS remote scanning because system property is set.");
            return;
        }
        Holder<ScheduledFuture<?>> task = new Holder<>();
        task.set(executor.scheduleWithFixedDelay(() -> {
            // Perform scanning, if allowed.
            try {
                // Skip if not allowed or already disabled.
                if (disabled || Boolean.getBoolean("ias.skipDisableScanning")) {
                    LOGGER.debug("IAS: Skipped IAS remote scanning because system property is set or the mod is already disabled.");
                    return;
                }

                // Create the client.
                HttpClient client = HttpClient.newBuilder()
                        .connectTimeout(TIMEOUT)
                        .version(HttpClient.Version.HTTP_2)
                        .followRedirects(HttpClient.Redirect.NORMAL)
                        .executor(Runnable::run)
                        .build();

                // Send the request.
                HttpResponse<Stream<String>> response = client.send(HttpRequest.newBuilder()
                        .uri(new URI("https://raw.githubusercontent.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/main/.ias/disabled_v1"))
                        .header("User-Agent", userAgent())
                        .timeout(TIMEOUT)
                        .GET()
                        .build(), HttpResponse.BodyHandlers.ofLines());

                // Validate the code.
                int code = response.statusCode();
                if (code < 200 || code > 299) return;

                // Check the lines.
                disabled = disabled || response.body().anyMatch(line -> {
                    line = line.strip();
                    return "ALL".equalsIgnoreCase(line) || version.equalsIgnoreCase(line);
                });

                // Return if normal.
                if (!disabled) {
                    LOGGER.debug("IAS: Completed remote disabling check. Not disabled.");
                    return;
                }

                // Log and stop task if disabled.
                LOGGER.error("IAS: The In-Game Account Switcher mod has been disabled by remote due to serious issues. Please, see the mod page for more information. ({})", version);
                ScheduledFuture<?> actualTask = task.get();
                if (actualTask == null) return;
                actualTask.cancel(false);
            } catch (Throwable t) {
                // Log into debug.
                LOGGER.debug("IAS: Unable to perform remote disabling check.", t);
            }
        }, 0L, 60L, TimeUnit.MINUTES));

        // Log.
        LOGGER.info("IAS: IAS has been loaded.");
    }

    /**
     * Closes the IAS.
     */
    public static void close() {
        // Log.
        LOGGER.info("IAS: Closing IAS...");

        // Shutdown the executor.
        shutdown:
        try {
            // Skip if doesn't exist.
            ScheduledExecutorService executor = IAS.executor;
            if (executor == null) break shutdown;

            // Shutdown.
            LOGGER.info("IAS: Shutting down IAS executor...");
            executor.shutdown();
            if (executor.awaitTermination(30L, TimeUnit.SECONDS)) {
                LOGGER.info("IAS: IAS executor shut down.");
                break shutdown;
            }

            // Shutdown forcefully.
            LOGGER.warn("IAS: Unable to shutdown IAS executor. Shutting down forcefully...");
            executor.shutdownNow();
            if (executor.awaitTermination(30L, TimeUnit.SECONDS)) {
                LOGGER.info("IAS: IAS executor shut down forcefully.");
                break shutdown;
            }

            // Unable to shut down.
            LOGGER.error("IAS: Unable to shutdown IAS executor forcefully.");
        } catch (InterruptedException e) {
            // Log.
            LOGGER.error("IAS: IAS executor interrupted while shutting down. Shutting down forcefully...", e);

            // Kill, if exists.
            ScheduledExecutorService executor = IAS.executor;
            if (executor != null) {
                executor.shutdownNow();
            }

            // Preserve interruption.
            Thread.currentThread().interrupt();
        }
        executor = null;

        // Destroy the UA.
        userAgent = null;

        // Write the disclaimers, if we can.
        try {
            IASStorage.disclaimers();
        } catch (Throwable ignored) {
            // NO-OP
        }

        // Log.
        LOGGER.info("IAS: IAS has been unloaded.");
    }

    /**
     * Gets the async executor for IAS.
     *
     * @return IAS executor
     * @throws NullPointerException If the executor is not available
     */
    @Contract(pure = true)
    @NotNull
    public static ScheduledExecutorService executor() {
        ScheduledExecutorService executor = IAS.executor;
        Objects.requireNonNull(executor, "IAS executor is not available.");
        return executor;
    }

    /**
     * Gets the user agent for usage in {@link MSAuth}.
     *
     * @return Current {@code User-Agent} value for HTTP requests
     * @throws NullPointerException If user agent wasn't set
     */
    @Contract(pure = true)
    @NotNull
    public static String userAgent() {
        String userAgent = IAS.userAgent;
        Objects.requireNonNull(userAgent, "IAS user agent is not set.");
        return userAgent;
    }

    /**
     * Gets the disabled state.
     *
     * @return Whether the mod is disabled remotely
     */
    @Contract(pure = true)
    public static boolean disabled() {
        return disabled;
    }

    /**
     * Initializes the IAS.
     *
     * @param gameDir       Game directory
     * @param configDir     Config directory
     * @param loader        Loader name
     * @param loaderVersion Loader version
     * @param modVersion    Mod version
     */
    public static void init(String loader, String modVersion, String loaderVersion) {
        // Log the info.
        String gameVersion = SharedConstants.getCurrentVersion().getName();
        LOGGER.info("IAS: Booting up... (version: {}, loader: {}, loader version: {}, game version: {})", modVersion, loader, loaderVersion, gameVersion);

        // Initialize the IAS.
        IAS.init(modVersion, loader, loaderVersion, gameVersion);
    }

    /**
     * Called on title screen initialization.
     *
     * @param minecraft   Minecraft instance
     * @param screen      Target screen
     * @param buttonAdder Adder function
     */
    @SuppressWarnings({"ChainOfInstanceofChecks", "ConstantValue"}) // <- Abstraction for Minecraft is not possible, mods break user non-nullness.
    public static void onInit(Minecraft minecraft, Screen screen, Consumer<Button> buttonAdder) {
        // Add title button.
        if (IASConfig.titleButton && screen instanceof TitleScreen) {
            // Calculate the position.
            int width = screen.width;
            int height = screen.height;
            Integer x = Expression.parsePosition(IASConfig.titleButtonX, width, height);
            Integer y = Expression.parsePosition(IASConfig.titleButtonY, width, height);

            // Couldn't parse position.
            if (x == null || y == null) {
                // Use default position.
                x = width / 2 + 104;
                y = height / 4 + 72;

                // Move out of any overlapping elements.
                for (int i = 0; i < 64; i++) {
                    boolean overlapping = false;
                    for (GuiEventListener child : screen.children()) {
                        // Skip if doesn't have pos.
                        if (!(child instanceof LayoutElement le) || child instanceof AbstractSelectionList<?>) continue;

                        // Skip if not overlapping.
                        int x1 = le.getX() - 4;
                        int y1 = le.getY() - 4;
                        int x2 = x1 + le.getWidth() + 8;
                        int y2 = y1 + le.getHeight() + 8;
                        if (x < x1 || y < y1 || (x + 20) > x2 || (y + 20) > y2) continue;

                        // Otherwise move.
                        x = Math.max(x, x2);
                        overlapping = true;
                    }
                    if (overlapping) continue;
                    break;
                }
            }

            // Add the button.
            ImageButton button = new ImageButton(x, y, 20, 20, BUTTON, btn -> minecraft.setScreen(new AccountScreen(screen)), Component.literal("In-Game Account Switcher"));
            button.setTooltip(Tooltip.create(button.getMessage()));
            button.setTooltipDelay(Duration.ofMillis(250L));
            buttonAdder.accept(button);
        }

        // Add servers button.
        if (IASConfig.serversButton && screen instanceof JoinMultiplayerScreen) {
            // Calculate the position.
            int width = screen.width;
            int height = screen.height;
            Integer x = Expression.parsePosition(IASConfig.serversButtonX, width, height);
            Integer y = Expression.parsePosition(IASConfig.serversButtonY, width, height);

            // Couldn't parse position.
            if (x == null || y == null) {
                // Use default position.
                x = width / 2 + 158;
                y = height - 30;

                // Move out of any overlapping elements.
                for (int i = 0; i < 64; i++) {
                    boolean overlapping = false;
                    for (GuiEventListener child : screen.children()) {
                        // Skip if doesn't have pos.
                        if (!(child instanceof LayoutElement le) || child instanceof AbstractSelectionList<?>) continue;

                        // Skip if not overlapping.
                        int x1 = le.getX() - 4;
                        int y1 = le.getY() - 4;
                        int x2 = x1 + le.getWidth() + 8;
                        int y2 = y1 + le.getHeight() + 8;
                        if (x < x1 || y < y1 || (x + 20) > x2 || (y + 20) > y2) continue;

                        // Otherwise move.
                        x = Math.max(x, x2);
                        overlapping = true;
                    }
                    if (overlapping) continue;
                    break;
                }
            }

            // Add the button.
            ImageButton button = new ImageButton(x, y, 20, 20, BUTTON, btn -> minecraft.setScreen(new AccountScreen(screen)), Component.literal("In-Game Account Switcher"));
            button.setTooltip(Tooltip.create(button.getMessage()));
            button.setTooltipDelay(Duration.ofMillis(250L));
            buttonAdder.accept(button);
        }

        // Add title text.
        if (IASConfig.titleText && screen instanceof TitleScreen) {
            // Calculate the position.
            int width = screen.width;
            int height = screen.height;
            Integer cx = Expression.parsePosition(IASConfig.titleTextX, width, height);
            Integer cy = Expression.parsePosition(IASConfig.titleTextY, width, height);
            Font font = minecraft.font;
            User user = minecraft.getUser();
            text = Component.translatable("ias.title", user != null ? user.getName() : "(broken by mods)");
            textX = cx == null || cy == null ? (width - font.width(text)) / 2 : switch (IASConfig.titleTextAlign) {
                case LEFT -> cx;
                case CENTER -> cx - font.width(text) / 2;
                case RIGHT -> cx - font.width(text);
            };
            textY = cx == null || cy == null ? height / 4 + 164 : cy;
        }

        // Add servers text.
        if (IASConfig.serversText && screen instanceof JoinMultiplayerScreen) {
            // Calculate the position.
            int width = screen.width;
            int height = screen.height;
            Integer cx = Expression.parsePosition(IASConfig.serversTextX, width, height);
            Integer cy = Expression.parsePosition(IASConfig.serversTextY, width, height);
            Font font = minecraft.font;
            User user = minecraft.getUser();
            text = Component.translatable("ias.title", user != null ? user.getName() : "(broken by mods)");
            textX = cx == null || cy == null ? (width - font.width(text)) / 2 : switch (IASConfig.serversTextAlign) {
                case LEFT -> cx;
                case CENTER -> cx - font.width(text) / 2;
                case RIGHT -> cx - font.width(text);
            };
            textY = cx == null || cy == null ? 5 : cy;
        }

        // Warn about invalid names.
        if (!IASConfig.nickWarns || !(screen instanceof ConnectScreen) || minecraft.getToastManager().getToast(SystemToast.class, NICK_WARN) != null) return;
        User user = minecraft.getUser();
        // Mods break non-nullness.
        //noinspection ConstantValue
        String name = user != null ? user.getName() : "";
        String key = IUtils.warnKey(name);
        if (key == null) return;

        // Display the toast.
        ToastManager manager = minecraft.getToastManager();
        manager.addToast(SystemToast.multiline(minecraft, NICK_WARN, Component.literal("In-Game Account Switcher"), Component.translatable(key, name)));
    }

    /**
     * Called on title screen drawing.
     *
     * @param screen   Target screen
     * @param font     Screen font
     * @param graphics Drawing graphics
     */
    @SuppressWarnings("ChainOfInstanceofChecks") // <- Abstraction for Minecraft is not possible.
    public static void onDraw(Screen screen, Font font, GuiGraphics graphics) {
        if (IASConfig.titleText && screen instanceof TitleScreen) {
            graphics.drawString(font, text, textX, textY, 0xFF_CC_88_88);
        }
        if (IASConfig.serversText && screen instanceof JoinMultiplayerScreen) {
            graphics.drawString(font, text, textX, textY, 0xFF_CC_88_88);
        }
    }

    /**
     * Logins into the minecraft.
     * Can be called from any thread.
     *
     * @param minecraft Minecraft instance
     * @param data      Login data
     * @return Future for logging in
     */
    public static CompletableFuture<Void> account(Minecraft minecraft, LoginData data) {
        // Check if not in-game.
        LOGGER.info("IAS: Received login request: {}", data);
        if (minecraft.player != null || minecraft.level != null || minecraft.getConnection() != null ||
                minecraft.cameraEntity != null || minecraft.gameMode != null || minecraft.isSingleplayer()) {
            return CompletableFuture.failedFuture(new FriendlyException("Changing accounts in world.", "ias.error.world"));
        }

        // Create everything async, because it lags.
        return CompletableFuture.runAsync(() -> {
            // Create the user.
            LOGGER.info("IAS: Creating user...");
            // I have no idea what are the OPTIONAL fields and the game
            // works FINE without them, even with chat reporting and parental control, etc.
            // etc., it may be some telemetry, it may be something else. If something is broken by this
            // feel free to submit an issue, if someone knows what this is, feel free to PR a fix,
            // I'm too lazy to fix anything related to telemetry or chat signatures/reports.
            boolean online = data.online();
            User.Type type = online ? User.Type.MSA : User.Type.LEGACY;
            User user = new User(data.name(), data.uuid(), data.token(), Optional.empty(), Optional.empty(), type);

            // Create various services.
            CompletableFuture<ProfileResult> profile = CompletableFuture.completedFuture(online ? minecraft.getMinecraftSessionService().fetchProfile(data.uuid(), true) : null);
            @SuppressWarnings("CastToIncompatibleInterface") // <- Mixin Accessor.
            MinecraftAccessor accessor = (MinecraftAccessor) minecraft;
            UserApiService apiService = online ? accessor.ias$authenticationService().createUserApiService(data.token()) : UserApiService.OFFLINE;
            UserApiService.UserProperties properties;
            try {
                properties = apiService.fetchProperties();
            } catch (Throwable ignored) {
                properties = UserApiService.OFFLINE_PROPERTIES;
            }
            CompletableFuture<UserApiService.UserProperties> propertiesFuture = CompletableFuture.completedFuture(properties);
            PlayerSocialManager social = new PlayerSocialManager(minecraft, apiService);
            ClientTelemetryManager telemetry = new ClientTelemetryManager(minecraft, apiService, user);
            ProfileKeyPairManager keyPair = ProfileKeyPairManager.create(apiService, user, minecraft.gameDirectory.toPath());
            ReportingContext reporting = ReportingContext.create(ReportEnvironment.local(), apiService);

            // Schedule to the main thread
            minecraft.execute(() -> {
                // Flush everything.
                LOGGER.info("IAS: Flushing user...");
                accessor.ias$user(user);
                accessor.ias$profileFuture(profile);
                accessor.ias$userApiService(apiService);
                accessor.ias$userPropertiesFuture(propertiesFuture);
                accessor.ias$playerSocialManager(social);
                accessor.ias$telemetryManager(telemetry);
                accessor.ias$profileKeyPairManager(keyPair);
                accessor.ias$reportingContext(reporting);
                minecraft.updateTitle();
                LOGGER.info("IAS: Flushed user.");
            });
        }, IAS.executor()).exceptionally(t -> {
            // Log it.
            LOGGER.error("IAS: Unable to log in: {}.", data, t);

            // Rethrow.
            throw new RuntimeException("Unable to change account to: " + data, t);
        });
    }
}
